### ISSUE TITLE
Step 5 - Import objects into FileNet Content Manager - Step 2 BAWTOS ROKS CLUSTER CP4BA

### ISSUE THREAD

**Issue by Rdecoster** [IBM/cp4ba-client-onboarding-scenario#4]
I am following the lab at step 5 -import objects into FileNet there is no BAWTOS in the ACCE page. However, there is a "TARGET" object-store class. Is this is what is supposed to be used. 
BAWTOS is also referenced in Step 4 - Import the Workflow Solution sub-Step 11. Through 14. 

I am using a preinstalled CP4BA ROKS cluster for this labs.

**Comment by swapnil-ibm** [comment]
Updated the instructions.
