### ISSUE TITLE
Step 6 - Import the Business Automation Application app 

### ISSUE THREAD

**Issue by Rdecoster** [IBM/cp4ba-client-onboarding-scenario#6]
Step 6 - Import the Business Automation Application app 

https://github.com/IBM/cp4ba-client-onboarding-scenario/tree/main/21.0.2/Solution%20Exports/Business%20Automation%20Navigator

When trying to complete 
step _26 -Choose the previously downloaded file ICNExportedConfiguration.properties and click on the Import button. You can close the summary dialog that pops up after the import is complete. Note that you may see a warning that says The following items already exist on this system. You can ignore this warning and continue with the import._
https://github.com/IBM/cp4ba-client-onboarding-scenario/blob/main/21.0.2/Step%206%20-%20Business%20Automation%20Application.md

[
](https://github.com/IBM/cp4ba-client-onboarding-scenario/blob/main/21.0.2/Step%206%20-%20Business%20Automation%20Application.md)

the ICNExportedConfiguration.properties does not have a format it was saved in so I just right-clicked and saved it from the source. But once I attempted to upload it I received an error depicted below saying that The Desktop configuration file cannot be imported because it was created from another version of IBM content Navigator. 

Is there a workaround for this or does a new file have to be uploaded? 

![image](https://user-images.githubusercontent.com/50038256/145646180-543ad9d0-4bc6-4193-bd1d-c872fd2736c5.png)

**Comment by swapnil-ibm** [comment]
Usage error. User didn't download the file correctly.
